apiVersion: v1
kind: Service
metadata:
  name: filura-app-service
spec:
  selector:
    app: filura-app-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer